// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int greater = 0;
		int lesser = 0;
		for (int i = 0; i < n; i++) {
			if (Math.random() > 0.5) {
				greater++;
			}
			else {
				lesser++;
			}

		}
		System.out.println("> 0.5: " + greater +" times");
		System.out.println("<= 0.5: " + lesser +" times");
		if ( lesser > 0) {
			System.out.println("Ratio: " + (double) greater / lesser);	
		}
	}
}
